### ISSUE TITLE
Twitch Client API key workaround, doesn't

### ISSUE THREAD

**Issue by 2cb-log** [P1xt/chingu-fcc-speedrun-challenge#5]
Getting a 404 returned from the URL created as a workaround to having to sign up for a Twitch API account:  https://wind-bow.gomix.me/twitch-api

Would be glad to simply delete that reference in a PR but seems it would better after a "bigger picture" strategy decision is made first.

**Comment by P1xt** [comment]
I wouldn't worry overmuch about it, future speedruns won't leverage the FCC projects so it'll become moot.

**Comment by 2cb-log** [comment]
I see.  So given that a strategic decision HAS been made, I will close this- as well as defer mulling what to backfill its portfolio slot with.  Thanks for the update.
